# Generated by Django 5.0.4 on 2024-04-28 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formpages", "0002_next_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="selectoption",
            name="next_page",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="formpages.page",
                verbose_name="dynamic next page",
            ),
        ),
    ]
