# Generated by Django 5.0.4 on 2024-04-29 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("formpages", "0004_survey"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={"verbose_name": "page", "verbose_name_plural": "pages"},
        ),
        migrations.AlterModelOptions(
            name="question",
            options={"verbose_name": "question", "verbose_name_plural": "questions"},
        ),
        migrations.AlterModelOptions(
            name="selectoption",
            options={
                "verbose_name": "select option",
                "verbose_name_plural": "select options",
            },
        ),
        migrations.AlterModelOptions(
            name="survey",
            options={"verbose_name": "survey", "verbose_name_plural": "surveys"},
        ),
    ]
